import { parse as parseYaml, stringify as stringifyYaml } from "stdlib/yaml";
import { join, relative, SEPARATOR } from "stdlib/path"
import { WalkError, walkSync } from "stdlib/fs";
import { DocumentSpec, Project } from "./project.ts"
import {
  emit,
  isAncestor,
  OverrideOp,
  ParsedDoc,
  ParseError,
  parseDocument,
  parseOverrides,
} from "./blocks.ts";
import {
  collectDeviations,
  type Deviation,
  DEVIATIONS_PATH,
  governanceWarnings,
  renderRegister,
} from "./deviations.ts";

export const COMPOSED_DIR = "docs";
/**
 * Institution override sources. Underscore-prefixed so Quarto treats the directory as project
 * material rather than as pages to render — the overrides are spliced into `docs/` instead.
 */
export const OVERRIDES_DIR = "_overrides";

const PREAMBLE_FILE = join(COMPOSED_DIR, "_preamble.qmd")

export interface ComposedDoc {
  ismsId: string;
  title: string;
  path: string;
  /** `_overrides/<ID>.qmd`, when the institution has one — the register cites it by line. */
  overrideSource?: string;
  /** Every override applied to this document, in baseline block order. */
  deviations: Deviation[];
}

/**
 * A non-`.qmd` file to mirror byte-for-byte into the composed tree. `origin` is carried through
 * to the console summary 
 */
export interface Asset {
  /** Absolute path to the file to copy bytes from. */
  path: string;
  origin: "baseline" | "override";
}

export interface ComposeResult {
  files: Map<string, string>;
  assets: Map<string, Asset>;
  docs: ComposedDoc[];
  /** Governance gaps worth naming. Not errors: composition still succeeded. */
  warnings: string[];
}

/**
 * Folds a path under the composed tree for collision comparison. 
 */
export function foldPath(rel: string): string {
  return rel.normalize("NFC").toLowerCase();
}

export async function compose(project: Project): Promise<ComposeResult> {
  const { root, baseline } = project;
  const baselineVersion = baseline.manifest.baseline_version;
  const files = new Map<string, string>();
  const docs: ComposedDoc[] = [];
  const warnings: string[] = [];

  // Hoisted: it does not vary per document, and the deviations register carries the identical
  // line, so both kinds of generated artefact are marked the same way.
  const banner =
    `<!-- GENERATED by \`isms compose\` from ISMS baseline ${baselineVersion}. DO NOT EDIT BY HAND. -->`;

  for (const spec of baseline.manifest.documents) {
    const baselinePath = join(baseline.dir, spec.file);
    const src = Deno.readTextFileSync(baselinePath);
    const parsed: ParsedDoc = parseDocument(baselinePath, src);

    const { path: overrideSource, ops } = loadOverrides(root, spec, parsed);

    const baseMeta = (parseYaml(parsed.frontMatter || "{}") ?? {}) as Record<string, unknown>;

    const body = emit(parsed.root, ops, true);
    const composed = `---\n${stringifyYaml(baseMeta, { sortKeys: true, lineWidth: 100 })}---\n\n${banner}\n${body}\n`;
    const relPath = join(COMPOSED_DIR, `${spec.id}-${slug(spec.title)}.qmd`);
    files.set(relPath, tidy(composed));

    // Anchors are resolved against `body`, before tidy() collapses blank lines and renumbers
    // them. Safe, because only positions relative to each other within this one string matter.
    const deviations = collectDeviations(body, ops, parsed.blocks);
    if (overrideSource) warnings.push(...governanceWarnings(overrideSource, deviations));

    docs.push({
      ismsId: spec.id,
      title: (baseMeta.title as string) ?? spec.title,
      path: relPath,
      overrideSource,
      deviations,
    })
  }

  const baseline_preamble = Deno.readTextFileSync(join(baseline.dir, PREAMBLE_FILE))

  files.set(DEVIATIONS_PATH, tidy(renderRegister(banner, baselineVersion, docs)));
  files.set(PREAMBLE_FILE, baseline_preamble)

  const { assets: baselineAssets, warnings: baselineAssetWarnings } = walkAssets(
    join(baseline.dir, COMPOSED_DIR),
    "baseline",
  );
  const { assets: overrideAssets, warnings: overrideAssetWarnings } = collectOverrideAssets(root);
  warnings.push(...baselineAssetWarnings, ...overrideAssetWarnings);

  const composedPaths = new Map<string, string>();
  for (const rel of files.keys()) composedPaths.set(foldPath(rel), rel);

  const assets = new Map<string, Asset>();
  const foldedAssetPaths = new Map<string, string>(); // folded composed path -> the rel that claimed it
  for (const [rel, asset] of [...baselineAssets, ...overrideAssets]) {
    const key = foldPath(rel);

    const docClash = composedPaths.get(key);
    if (docClash !== undefined) {
      throw new Error(
        `${asset.origin} asset ${rel} (from ${asset.path}) collides with the composed document ` +
        `at ${docClash}. ` +
        `An asset can never share a composed path with a document; rename the source file.`,
      );
    }

    foldedAssetPaths.set(key, rel);
    assets.set(rel, asset);
  }

  return { files, assets, docs, warnings };
}

/**
 * Walk a docs-shaped directory tree and map every non-`.qmd` file it contains to its position
 * under the composed `docs/`. Shared by the baseline walk (`_extensions/isms/docs/`) and the
 * institution walk (`_overrides/`, see `collectOverrideAssets`) 
 */
function walkAssets(dir: string, origin: Asset["origin"]): { assets: Map<string, Asset>; warnings: string[] } {
  const assets = new Map<string, Asset>();
  const warnings: string[] = [];
  for (const entry of walkSync(dir, { includeDirs: false, followSymlinks: false, skip: [/\.qmd$/i] })) {
    const relFromRoot = relative(dir, entry.path);
    const rel = join(COMPOSED_DIR, relFromRoot);
    if (entry.isSymlink) {
      warnings.push(`${origin} asset ${rel} is a symlink and was not copied`);
      continue;
    }
    if (relFromRoot.split(SEPARATOR).some((segment: any) => segment.startsWith("."))) {
      warnings.push(`${origin} asset ${rel} is a dotfile, or inside one, and was not copied`);
      continue;
    }
    assets.set(rel, { path: entry.path, origin });
  }
  return { assets, warnings };
}

/**
 * Every non-`.qmd` file under `<root>/_overrides/` is mirrored to the same relative position
 * under the composed `docs/` 
 */
function collectOverrideAssets(root: string): { assets: Map<string, Asset>; warnings: string[] } {
  try {
    return walkAssets(join(root, OVERRIDES_DIR), "override");
  } catch (err: any) {
    // No `_overrides/` at all is the normal case — most adopting institutions have no local
    if (err instanceof WalkError && err.cause instanceof Deno.errors.NotFound) {
      return { assets: new Map(), warnings: [] };
    }
    throw err;
  }
}

/**
 * Read the institution's override file for one baseline document, if it has one.
 *
 * Overrides live in `<root>/_overrides/<ISMS-ID>.qmd` — one file per document, keyed on the
 * ID rather than the title, so retitling a baseline document does not orphan its overrides.
 * Absence is the normal case: a document with no override file is adopted verbatim.
 */
function loadOverrides(
  root: string,
  spec: DocumentSpec,
  parsed: ParsedDoc,
): { path?: string; ops: Map<string, OverrideOp> } {
  // The relative path is what the deviations register cites; an absolute one would leak the
  // composing machine's filesystem into a rendered audit page. Errors keep the absolute path,
  // where a full path is what you want in a terminal.
  const rel = join(OVERRIDES_DIR, `${spec.id}.qmd`);
  const path = join(root, rel);
  let src: string;
  try {
    src = Deno.readTextFileSync(path);
  } catch (err) {
    if (err instanceof Deno.errors.NotFound) return { ops: new Map() };
    throw err;
  }

  const { document, ops } = parseOverrides(path, src);
  if (document !== undefined && document !== spec.id) {
    throw new ParseError(path, 1, `front matter says document: ${document}, but this file overrides ${spec.id}`);
  }

  for (const op of ops.values()) {
    // A typo in a block ID would otherwise be a silent no-op, which is the worst possible
    // outcome for something an approver has signed off on.
    if (!parsed.blocks.has(op.id)) {
      throw new ParseError(
        path,
        op.line,
        `${spec.id} has no block "${op.id}". Overridable blocks: ${[...parsed.blocks.keys()].join(", ")}`,
      );
    }
    // Replacing or deleting a block discards its children, so an override on a descendant
    // of one would never reach the output. Fail loudly rather than drop it.
    if (op.mode !== "replace" && op.mode !== "delete") continue;
    for (const inner of ops.values()) {
      if (isAncestor(op.id, inner.id)) {
        throw new ParseError(
          path,
          inner.line,
          `override "${inner.id}" sits inside "${op.id}", which is overridden with ` +
          `mode=${op.mode} (line ${op.line}) and would discard it`,
        );
      }
    }
  }
  return { path: rel, ops };
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}


/** Collapse the blank-line noise that splicing inevitably produces. */
function tidy(s: string): string {
  return s.replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "") + "\n";
}
