import { parse as parseYaml, stringify as stringifyYaml } from "stdlib/yaml";
import { join } from "stdlib/path"
import { Project } from "./project.ts"
import { Block, emit, OverrideOp, ParsedDoc, parseDocument } from "./blocks.ts";

export const COMPOSED_DIR = "docs";

export interface ComposedDoc {
  ismsId: string;
  title: string;
  path: string;
}

export interface ComposeResult {
  files: Map<string, string>;
  docs: ComposedDoc[];
}

export async function compose(project: Project): Promise<ComposeResult> {
  const { root, baseline } = project;
  const baselineVersion = baseline.manifest.baseline_version;
  const files = new Map<string, string>();
  const docs: ComposedDoc[] = [];

  for (const spec of baseline.manifest.documents) {
    const baselinePath = join(baseline.dir, spec.file);
    const src = Deno.readTextFileSync(baselinePath);
    const parsed: ParsedDoc = parseDocument(baselinePath, src);

    // TODO: overrides
    let ops = new Map<string, OverrideOp>();

    const baseMeta = (parseYaml(parsed.frontMatter || "{}") ?? {}) as Record<string, unknown>;

    const banner =
      `<!-- GENERATED by \`isms compose\` from ISMS baseline ${baselineVersion}. DO NOT EDIT BY HAND. -->`;

    const body = emit(parsed.root, ops, true);
    const composed = `---\n${stringifyYaml(baseMeta, { sortKeys: true, lineWidth: 100 })}---\n\n${banner}\n${body}\n`;
    const relPath = join(COMPOSED_DIR, `${spec.id}-${slug(spec.title)}.qmd`);
    files.set(relPath, tidy(composed));

    docs.push({
      ismsId: spec.id,
      title: baseMeta.title as string,
      path: relPath,
    })
  }
  return { files, docs };
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}


/** Collapse the blank-line noise that splicing inevitably produces. */
function tidy(s: string): string {
  return s.replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "") + "\n";
}
